# Generated by Django 4.0.4 on 2022-06-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='subtitulo',
            field=models.CharField(default='Nada', max_length=120),
        ),
    ]
