# Generated by Django 4.0.4 on 2022-06-28 18:41

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_categoria_posteo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='titulo', unique=True),
            preserve_default=False,
        ),
    ]
