# Generated by Django 4.0.4 on 2022-06-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_posteo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
